### ISSUE TITLE
unidentifiable Chinese code

### ISSUE THREAD

**Issue by DreamPWJ** [valb3r/flowable-bpmn-intellij-plugin#180]
![image](https://user-images.githubusercontent.com/16730031/90866557-aafda200-e3c6-11ea-99e0-3e4d154997af.png)

**Comment by valb3r** [comment]
Thanks, will have a look

**Comment by DreamPWJ** [comment]
After a long time of searching, I finally found a good plug-in for this process in IDEA, hoping to continue to perfect the great work@valb3r

**Comment by DreamPWJ** [comment]
Yes, the fix worked perfectly. Thank you very much @valb3r
