### ISSUE TITLE
Horizontal and vertical scroll bar in the design 

### ISSUE THREAD

**Issue by bijeshchandran** [valb3r/flowable-bpmn-intellij-plugin#206]
**Is your feature request related to a problem? Please describe.**
A horizontal and vertical scroll bar will really help. 
Now its difficult to work with big processes. 

**TBD:**
- [x] Scroll bars that follow diagram drag and zoom
- [x] Reset camera to center
- [x] ~When scrollbars are present - disable absolutely free navigation~
- [x] Handle keyboard shortcuts (Ctrl + / Ctrl -, Arrow keys)
- [x] ~Plugin settings to disable scrollbars~
- [x] ~Plugin settings to change zoom ratios~

**Comment by valb3r** [comment]
Hi @bijeshchandran, thanks for the suggestion. Yes, it is definitely doable, the only thing due to workload this will not appear within 1-2 months.

**Comment by valb3r** [comment]
@bijeshchandran I've added scrollbars. It is not released, but you can try these meanwhile:
Flowable: [flowable-bpmn-plugin.zip](https://github.com/valb3r/flowable-bpmn-intellij-plugin/files/6051973/flowable-bpmn-plugin.zip)
Activiti: [activiti-bpmn-plugin.zip](https://github.com/valb3r/flowable-bpmn-intellij-plugin/files/6051971/activiti-bpmn-plugin.zip)

**Comment by valb3r** [comment]
@bijeshchandran v0.4.5 has these changes released

**Comment by bijeshchandran** [comment]
works like charm.   Thank you for adding this feature at such short time.
With best regards,

Bijesh Chandran
