### ISSUE TITLE
cannot find some idea dependencies we used in maven central anymore...

### ISSUE THREAD

**Issue by XenoAmess** [valb3r/flowable-bpmn-intellij-plugin#208]
see https://youtrack.jetbrains.com/issue/JBR-3089

**Comment by valb3r** [comment]
@XenoAmess 
Their EAP seems to broke dependencies. I've observed a bit different error to yours, but after my fix, CI/CD is able to build a plugin

My solution is in these commits:
https://github.com/valb3r/flowable-bpmn-intellij-plugin/commit/e78b7b39ae8a90361138c39ad862fe6cca021dc7
https://github.com/valb3r/flowable-bpmn-intellij-plugin/commit/79106b50c3a3f2ec2bf2b20a2f37da71d5bd7acb
https://github.com/valb3r/flowable-bpmn-intellij-plugin/commit/349d649cbcd2ffdf9f599c53b8b18894adef5f3c

Or you can clone the `feature/FBP-206-add-scroll-bar-support` branch and apply changes **only from gradle files**:
https://github.com/valb3r/flowable-bpmn-intellij-plugin/compare/feature/FBP-206-add-scroll-bar-support

That branch builds perfectly in CI/CD
https://github.com/valb3r/flowable-bpmn-intellij-plugin/runs/1869349045

I think this is something related to:
https://github.com/JetBrains/gradle-intellij-plugin/issues/369

**Comment by XenoAmess** [comment]
please tel me and close this issue when solved in branch master

**Comment by valb3r** [comment]
@XenoAmess fixed in master

**Comment by XenoAmess** [comment]
@valb3r I saw it. Thanks!
