### ISSUE TITLE
flowable-bpmn-intellij-plugin couldn't be installed properly on Windows 10

### ISSUE THREAD

**Issue by quan-qiu** [valb3r/flowable-bpmn-intellij-plugin#230]
Intellij version: Ultimate 2020.2.3
Flowable BPMN visulizer version：0.4.6
Below were exceptions after installed flowable-bpmn-intellij-plugin

There were number of namespace in red in process-1.xml 

`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:flowable="http://flowable.org/bpmn"
             xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
             xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI"
             typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath"
             targetNamespace="http://www.flowable.org/processdef">
    <process id="process-1" name="process-1" isExecutable="true">
    </process>
    <bpmndi:BPMNDiagram id="BPMNDiagram_process-1">
        <bpmndi:BPMNPlane bpmnElement="process-1" id="BPMNPlane_process-1">
        </bpmndi:BPMNPlane>
    </bpmndi:BPMNDiagram>
</definitions>`

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at fuck_you.al.lambda$projectOpened$0(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 6 more

**Comment by valb3r** [comment]
@quan-qiu Thanks for feedback, but are you sure this stacktrace is relevant to this plugin? As this plugin does not use GSON.
Can you please elaborate your actions and what do you observe?
I've tested it on Windows with same vanilla IntelliJ version as yours and plugin works OK

**Comment by quan-qiu** [comment]
Thanks for your reply. Sorry, you are alright, BPMN plugin has been already
installed. Because I am new to the BPMN, do you know where I can download a
simple project that I can kick off with? Thanks again for your kind
assistance.

Regards

**Comment by valb3r** [comment]
@quan-qiu I think https://github.com/flowable/flowable-examples is good place to start with Flowable-BPMN
