### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by twel** [valb3r/flowable-bpmn-intellij-plugin#240]
**Describe the bug**
After plugin installation, the plugin doesn't work opening a bpmn file

**To Reproduce**
1. Install plugin (v0.4.6.2)
2. Open bpmn file

**BPMN definition**

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<diagram xmlns="http://www.omg.com/di/1.0.0">
<!-- BPMN to use to reproduce the issue -->
</diagram>
```

**Expected behavior**
No tabs or context options, opening a bpmn file.
Same file opens well in eclipse, and possible to visualize the diagram.

**Screenshots**
NA

**IntelliJ version (please complete the following information):**
 - Edition: Ultimate Edition
 - Version: 2021.2
 - SO: Linux
 
**Additional context**
NA

**Comment by valb3r** [comment]
@twel It looks like you are using the plugin as a generic-purpose BPMN editor. What is the extension of your file? 
This plugin is **not a generic** BPMN editor. It is designed to work with very specific BPMN dialects, particularly Activiti and Flowable BPMN dialects. Flowable & Activiti (6.x) BPMN dialects have `bpmn20.xml` file extension and have very specific XML namespaces.

**Comment by twel** [comment]
Hi,

We're using activiti, and I've seen previously the plugin working on other
colleague's machine (older versions of IntelliJ and the plugin)

<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:activiti="http://activiti.org/bpmn"
xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC"
xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI"
typeLanguage="http://www.w3.org/2001/XMLSchema"
expressionLanguage="http://www.w3.org/1999/XPath"
targetNamespace="/processes/processes-activiti/Ex">

In the description you say "Activiti 6.x and older BPMN diagrams". Can you
clarify? It will work on a activiti 4 or 5 diagram?

**Comment by valb3r** [comment]
The plugin will work with files having the extension `bpmn20.xml`. I.e. `diagram.bpmn20.xml`. It should work for Activity 6.x and Activiti 5.x. Most probably it will work for Activiti 4, but I haven't done much testing there.

**Comment by twel** [comment]
OK, I understand.
It worked before on a *.bpmn file(activiti 4) on a previous version of the plugin and IntelliJ. 
Guess we'll have to use eclipse....

**Comment by valb3r** [comment]
I can add a plugin setting to relax this requirement, so you would be able to open the file with `*.bpmn` extension too

**Comment by valb3r** [comment]
@twel Here is patched version of the plugin 
[activiti-bpmn-plugin.zip](https://github.com/valb3r/flowable-bpmn-intellij-plugin/files/6959623/activiti-bpmn-plugin.zip)

You can enable this via settings:
![Peek 2021-08-10 09-52](https://user-images.githubusercontent.com/18463491/128822624-80eacfeb-6ccc-4367-a7a6-0a826667eb6e.gif)

To install plugin from disk:
https://stackoverflow.com/questions/36940630/how-to-download-a-plugin-to-disk-for-offline-installation-in-intellij

**Comment by twel** [comment]
I was testing it by renaming the files to bpmn20.xml and I've managed to open the diagram. 
However, trying to open a second diagram the view was always showing the first file and I could open more(renamed) diagrams.

Opening them directly in *.bpmn would be amazing, going to test it!

I've previously **wrongly** stated I'm using activiti 4 but I'm using **activiti 5.x**

**Comment by twel** [comment]
It's working!!
Great!!
Many thanks!!
