### ISSUE TITLE
Plugin displays blank window when opening *.bpmn20.xml

### ISSUE THREAD

**Issue by joemcerlane** [valb3r/flowable-bpmn-intellij-plugin#243]
**Describe the bug**
Click on any of the .bpmn20.xml files and view BPMN diagram opens a blank window

In this instance I am using a simple test file:

<?xml version="1.0" encoding="UTF-8"?>

<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
			 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:activiti="http://activiti.org/bpmn"
			 xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC"
			 xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema"
			 expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.activiti.org/test">

	<process id="my-process">

		<startEvent id="start" />
		<sequenceFlow id="flow1" sourceRef="start" targetRef="someTask" />

		<userTask id="someTask" name="Activiti is awesome!" />
		<sequenceFlow id="flow2" sourceRef="someTask" targetRef="end" />

		<endEvent id="end" />

	</process>

</definitions>

**Expected behavior**
I'd like to view a diagram, I've attached a screenshot to show the behaviour when view opened via "diagrams"->"Show BPMN Designer 2.0..." in which you can see the diagram displayed.

**Screenshots**
Added screenshoot
![Screen Shot 2021-08-23 at 3 06 04 PM](https://user-images.githubusercontent.com/5169157/130526053-883a0443-afce-4fb6-9b29-431d89cb066a.png)

IntelliJ IDEA 2019.3.5 (Ultimate Edition)
Build #IU-193.7288.26, built on May 6, 2020
Licensed to william mcerlane
You have a perpetual fallback license for this version
Subscription is active until April 29, 2022
Runtime version: 11.0.6+8-b520.66 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 5964M
Cores: 12
Registry: 
Non-Bundled Plugins: Key Promoter X, MavenRunHelper, activiti-bpmn-visualizer, aws.toolkit, com.jinsihou.react.snippets, flowable-bpmn-visualizer, google-java-format, org.sonarlint.idea
 
**Additional context**

**Comment by valb3r** [comment]
@joemcerlane Thanks for the feedback, but please provide the entire BPMN file, it is impossible to debug issues without it. Also, this plugin requires `DI (Diagram Tags)` to display diagrams (this is the way Flowable and Activit 6.x modelers work), so maybe your XML is missing DI section

**Comment by joemcerlane** [comment]
Thanks for the swift response, that is the full content of the BPMN file I took from here: https://github.com/Activiti/activiti-unit-test-template/blob/master/src/test/resources/org/activiti/test/my-process.bpmn20.xml
Not sure what DI (Diagram Tags) if this https://www.jetbrains.com/help/idea/diagrams.html then I'm good as that is how I was able to display the diagram in the screenshot, however flowable/activiti plugin don't wish to play ball
Any verification steps you would recommend on my end?

**Comment by valb3r** [comment]
The DI (Diagram Tags) is a `bpmndi:BPMNDiagram` XML tag and its children. For example:
https://github.com/valb3r/flowable-bpmn-intellij-plugin/blob/master/activiti-xml-parser/src/test/resources/duplicates.bpmn20.xml#L17

The example you have provided lacks these, as Activiti BPMN engine does not need `bpmndi:BPMNDiagram`, it only needs process definition. `bpmndi:BPMNDiagram` tag defines human-friendly element layout that is shown to the user. This plugin requires them and they are created when you are using Activiti-modeler as well

**Comment by valb3r** [comment]
No diagram rendering might be done within 
https://github.com/valb3r/flowable-bpmn-intellij-plugin/issues/203

**Comment by joemcerlane** [comment]
Gotcha @valb3r thanks for clearing up the confusion 👍
