### ISSUE TITLE
UserTask - support Candidate user and Groups

### ISSUE THREAD

**Issue by XiaoyuZhann** [valb3r/flowable-bpmn-intellij-plugin#309]
UserTask should support candidate user and candidate groups field:
 - [ ] Basic support (text only fields)
 - [ ] (Extra) Connect to DB to fetch available users and groups
 
**ORIGINAL**:
There are no two fields CandidateGroup and CandidateUsers in the plug-in. Are there other ways to add these two fields?
Can it be added through Form properties?

**Comment by valb3r** [comment]
@XiaoyuZhann Not all fields are implemented currently, I'll add these. You are referring to UserTask right?
