### ISSUE TITLE
I installed version 0.5.0 on my Mac Intellij, installed the Plugin right-clicked and viewed BPM (Flowable) Diagram ... I can't see anything

### ISSUE THREAD

**Issue by DerekWWestAwesomeDeveloper** [valb3r/flowable-bpmn-intellij-plugin#324]
**I can't see or edit any BPMN diamgrams (I am on a Mac and using Intellij IDEA 20221.1 (Ultimate Edition) **
I installed version 0.5.0 on my Mac Intellij, installed the Plugin right-clicked and viewed BPM (Flowable) Diagram ... I can't see anything

**To Reproduce**

1. Go to 'any bpm20.xml file in your project'
2. Right Click on the xml and click viewed BPM (Flowable) Diagram
3. I Don't see anything
4. I can't navigate to any view of my BPMN diagram at all.

Was this thing tested on a mac?

**BPMN definition**

```xml 1
<?xml version="1.0" encoding="UTF-8"?>
<definitions
        xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
        xmlns:flowable="http://flowable.org/bpmn"
        targetNamespace="Examples">

    <process id="oneTaskProcess" name="The One Task Process">
        <startEvent id="theStart" />
        <sequenceFlow id="flow1" sourceRef="theStart" targetRef="theTask" />
        <userTask id="theTask" name="my task" flowable:assignee="kermit" />
        <sequenceFlow id="flow2" sourceRef="theTask" targetRef="theEnd" />
        <endEvent id="theEnd" />
    </process>

</definitions>
```
``` xml 2
<?xml version="1.0" encoding="UTF-8"?>
<definitions
    xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
    xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC"
    xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI"
    xmlns:flowable="http://flowable.org/bpmn"
    typeLanguage="http://www.w3.org/2001/XMLSchema"
    expressionLanguage="http://www.w3.org/1999/XPath"
    targetNamespace="http://www.flowable.org/processdef">
    <process id="newTemplateCreationRequest"
      name="A simple request for a new template." isExecutable="true">
        <startEvent id="start" />
        <sequenceFlow sourceRef="start" targetRef="reviewTemplateRequest" />
        <userTask id="reviewTemplateRequest" name="Review submitted template request"
          flowable:candidateGroups="editors" />
        <sequenceFlow sourceRef="reviewTemplateRequest" targetRef="decision" />
        <exclusiveGateway id="decision" />
        <sequenceFlow sourceRef="decision" targetRef="templateRequestApproved">
            <conditionExpression xsi:type="tFormalExpression">
                <![CDATA[${approved}]]>
            </conditionExpression>
        </sequenceFlow>
        <sequenceFlow sourceRef="decision" targetRef="templateRequestApprovedRejected">
            <conditionExpression xsi:type="tFormalExpression">
                <![CDATA[${!approved}]]>
            </conditionExpression>
        </sequenceFlow>
        <serviceTask id="templateRequestApproved" name="Publish the approved template Metadata."
          flowable:class="com.baeldung.service.PublishArticleService" />
        <sequenceFlow sourceRef="templateRequestApproved" targetRef="end" />
        <serviceTask id="templateRequestApprovedRejected" name="Send out rejection email"
          flowable:class="com.baeldung.service.SendMailService" />
        <sequenceFlow sourceRef="templateRequestApprovedRejected" targetRef="end" />
        <endEvent id="end" />
    </process>
</definitions>
```
**Expected behavior**

**Screenshots**

**IntelliJ version (please complete the following information):**
 - Edition: [e.g. Ultimate]
 - Version [e.g. 2020.1]
 
**Additional context**

**Comment by DerekWWestAwesomeDeveloper** [comment]
Based off of [this](https://github.com/valb3r/flowable-bpmn-intellij-plugin/issues/225) issue I added a few xml tags ...
Now I just get a [Loading...] that never completes and I don't see a process anywhere that is doing anything?

**Comment by valb3r** [comment]
@DerekWWestAwesomeDeveloper Thanks for your feedback. 
> Was this thing tested on a Mac?

Yes

As for yours
> BPMN definition

You should see these errors
<img width="1169" alt="Screenshot 2022-11-12 at 07 55 26" src="https://user-images.githubusercontent.com/18463491/201459756-d8d60903-fd66-4af8-a5a8-245842ed92f0.png">
:
<img width="1157" alt="Screenshot 2022-11-12 at 07 54 44" src="https://user-images.githubusercontent.com/18463491/201459754-77cc8a3e-5f7e-4a37-a38b-46ce9fda85fa.png">

Because the diagram is invalid, like you saw at https://github.com/valb3r/flowable-bpmn-intellij-plugin/issues/225


> Now I just get a [Loading...] that never completes and I don't see a process anywhere that is doing anything?

**Please provide the file** you are testing on. Also, did you observe any exception (red blinking exclamation sign at the right corner of IntelliJ). Manual editing of BPMN file is not something what is to be expected to be easy

**Another question** - Why not to create the diagram directly inside plugin, why you are editing XML file manually?

**Comment by valb3r** [comment]
Closing as stale
