### ISSUE TITLE
Display id, name and documentation for all elements

### ISSUE THREAD

**Issue by filiphr** [valb3r/flowable-bpmn-intellij-plugin#33]
I haven't looked at the code and how everything is done. 

It would be great if the `id`, `name` and `documentation` are displayed for every element. For example [this](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/signal/SignalEventTest.testSignalWaitOnUserTaskBoundaryEvent.bpmn20.xml) with a user task and boundary signal.

Not sure if you are using your own parser of the XML or you are reusing the `BpmnModel` from Flowable. If you are reusing the `BpmnModel` you might benefit of not needing to do the parsing yourself and you can focus on the drawing and displaying the information.

**Comment by valb3r** [comment]
Good point, 
I use my own XML parsing mostly to have a feeling of how it is to work with Kotlin in a real project. If FasterXML will cause more problems than I've already seen, probably will use Flowable parser

**Comment by filiphr** [comment]
Just FYI the Flowable Parser doesn't use FasterXML, but uses native XML streaming from Java to do the parsing.

**Comment by valb3r** [comment]
UI undo-redo in 
https://github.com/valb3r/flowable-bpmn-intellij-plugin/issues/48

**Comment by valb3r** [comment]
To be done in parts, initial scope declared in: #61

**Comment by filiphr** [comment]
What I meant mostly for this is that you can do it based on a common base element (similar to how the Flowable Model looks like). Without the need to do something special when a new element is added.

**Comment by valb3r** [comment]
Thanks for the input,
Yes, I get the idea, but the problem is current XML parser as it uses declarative structure - it is rather complicated to handle unknown objects. Changing parser without tests will be time-consuming, so it looks like it is easier to define all elements. #61 is to handle basic structure for elements without complexities like an event listener
