### ISSUE TITLE
Bundled Camunda XSD is missing custom extensions

### ISSUE THREAD

**Issue by teake** [valb3r/flowable-bpmn-intellij-plugin#335]
**Describe the bug**
The Bundled camunda XSD is missing custom extensions, which results in IntelliJ wrongly complaining about e.g. `camunda:asyncBefore="true"` being an unallowed attribute.

**To Reproduce**
1. Open a `bpmn` file that has a custom Camunda extension in the XML
2. IntelliJ will highlight as an error.

**Expected behavior**
That IntelliJ will not flag custom Camunda XML extensions as errors.

**Screenshots**
<img width="366" alt="Screenshot 2023-02-17 at 16 51 24" src="https://user-images.githubusercontent.com/1324716/219701415-ec6f5934-b212-4d9a-bd67-a49b7ad41faf.png">

**IntelliJ version (please complete the following information):**
 - Edition: Ultimate
 - Version 2022.3.2
 
**Additional context**
List of custom Camunda extensions: https://docs.camunda.org/manual/7.14/reference/bpmn20/custom-extensions/.
Related discussion: https://github.com/camunda/camunda-modeler/issues/1972.

Perhaps the easiest way to fix this is to remove the bundled camunda-1.0.xsd file?

**Comment by valb3r** [comment]
@teake Thanks for feedback,

> Perhaps the easiest way to fix this is to remove the bundled camunda-1.0.xsd file?

Yes it would be easiest, but I think supporting correct schema is better. Need to check how much of work it is there - I would prefer having 95% complete XSD schema compared to none

**Comment by teake** [comment]
Yes, I agree that having the correct schema would be better. But then it would need to be 100% complete IMHO; otherwise IntelliJ will complain about non-allowed attributes and elements when you use those that are not in the XSD,, which is really annoying and distracts from actual errors in the code.

**Comment by teake** [comment]
@valb3r Yes, that sounds like a good comprise.

**Comment by valb3r** [comment]
@teake Here is Camunda plugin build that allows to disable XSD schemas provided by plugin:
[camunda-bpmn-plugin.zip](https://github.com/valb3r/flowable-bpmn-intellij-plugin/files/10950571/camunda-bpmn-plugin.zip)

Guide to install:
https://www.youtube.com/watch?v=tfSAEMSIrqA&t=42s

Check it, if it is OK I'll merge it into master

(built from https://github.com/valb3r/flowable-bpmn-intellij-plugin/tree/bugfix/FBP-335-allow-disabling-xsd)
