### ISSUE TITLE
Cannot undo if you do a change in the Diagram view

### ISSUE THREAD

**Issue by filiphr** [valb3r/flowable-bpmn-intellij-plugin#34]
**Describe the bug**
Change something in the Diagram View and try to undo the change.

**Expected behaviour**
Be able to undo a change done in the diagram

**IntelliJ version (please complete the following information):**
IntelliJ IDEA 2020.1.2 Preview (Ultimate Edition)
Build #IU-201.7846.6, built on May 13, 2020

**Comment by valb3r** [comment]
Good point, 
Architecture is already diff-event based, need to expose this to UI

**Comment by filiphr** [comment]
One other thing I noticed (not sure if it is related to this) is that the UI is not linked to the BPMN document. It is a dedicated section. Does it make sense to have it as a split view in the same section as the document? Similar to how the markdown support from IntelliJ looks like

**Comment by valb3r** [comment]
Quite interesting suggestion, this needs some investigation as I want to release the same plugin for Eclipse after done with IntelliJ and currently it is doable with minor changes in UI part. 
Stuff like markdown plugin will probably couple some parts of plugin to IDE more tightly than I would expect. 
But I like the idea and here is ticket for its investigation:
https://github.com/valb3r/flowable-bpmn-intellij-plugin/issues/35
