### ISSUE TITLE
Plugin only works with file type *.bpmn20.xml

### ISSUE THREAD

**Issue by thomasulllrich** [valb3r/flowable-bpmn-intellij-plugin#359]
The bpmn files in my project have the file suffix *.bpmn. So I added this for the plugin's file types. But it is not recognizing the new file type. There isn't showing the option to display the diagram by clicking the right mouse button on the file in the file tree or in the opened file

**Comment by valb3r** [comment]
@thomasulllrich 
Please check the following FAQ section:
https://github.com/valb3r/flowable-bpmn-intellij-plugin#q-my-files-for-activitiflowable-engine-have-bpmn-extension-and-not-bpmn20xml-how-can-i-open-them

**Comment by thomasulllrich** [comment]
Thx! Haven't seen this text. Now it works!
