### ISSUE TITLE
Support of skipExpressions

### ISSUE THREAD

**Issue by thomasulllrich** [valb3r/flowable-bpmn-intellij-plugin#375]
Hi!

Are you already supporting skipExpressions? Haven't seen anything about it in the plugin.

BR,
Thomas

**Comment by valb3r** [comment]
@thomasulllrich 
Hi, yes:
![Uploading Screenshot 2023-10-09 at 19.10.47.png…]()

**Comment by thomasulllrich** [comment]
Is it for all kinds of plugins available or only for specific ones?

**Comment by valb3r** [comment]
All (flowable,activiti,camunda), but the expression itself is supported only on:
Flowable: ServiceTask, UserTask
Activiti: UserTask
Camunda:  ServiceTask, UserTask

If you know other elements should support it, please write it here (as well as which BPMN engine it is), I'll add support

**Comment by thomasulllrich** [comment]
I was using the Activiti Plugin. I switched to the Flowable Plugin. Now it is working. Thx!

**Comment by valb3r** [comment]
@thomasulllrich Please note you should use Flowable plugin if you use Flowable BPMN engine, if you use Activiti BPMN - it might be necessary for me to add skipExpressions to some element (I might missed that), as for Activiti plugin only UserTask supports it
