### ISSUE TITLE
Unable to view files ending in(. bpmn)

### ISSUE THREAD

**Issue by blankplace** [valb3r/flowable-bpmn-intellij-plugin#379]
**Describe the bug**
After using the plugin, only XML format files can be opened, and bpmn files cannot be opened

**Screenshots**
![image](https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/46878354/09b8b557-fecb-4ac7-aaa2-ff47ca0e9d8a)
![image](https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/46878354/7fbc8d19-9e0a-42e9-b2a9-16174c15d165)

**IntelliJ version (please complete the following information):**
 
 - Version2023.1.2
 
**Additional context**

**Comment by valb3r** [comment]
@blankplace Please check FAQ section:
https://github.com/valb3r/flowable-bpmn-intellij-plugin#q-my-files-for-activitiflowable-engine-have-bpmn-extension-and-not-bpmn20xml-how-can-i-open-them
