### ISSUE TITLE
Chinese garbled characters

### ISSUE THREAD

**Issue by g591790803** [valb3r/flowable-bpmn-intellij-plugin#381]
idea version:2023.02
plugin version: Activiti BPMN visualizer 0.5.4.2

the chinese in xml is normal ，but in 【View BPMN (Activiti) Diagram】 is garbled characters.
i set file-encoding 'UTF-8' , But it didn't work.
![image](https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/19728138/a2a46d35-6e91-461f-be94-b67d35d3f2aa)

**Comment by valb3r** [comment]
@g591790803 Thanks for feedback. Can you check which font is being used:

https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/18463491/c9d30260-4675-46cb-a80b-d438a8f28919

You may try to change the font used there, as it might not support UTF-8

**Comment by g591790803** [comment]
current front is  Courier.
change front to 【宋体】，the chinese in 【View BPMN (Activiti) Diagram】 is normal .
![image](https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/19728138/76774109-1275-4379-adc5-624b374676ab)

thanks!!!
