### ISSUE TITLE
请问我在流程图中的节点设置了 Assignee 值，为什么启动流程后，任务表的 ASSIGNEE_ 值为空

### ISSUE THREAD

**Issue by Yuqn** [valb3r/flowable-bpmn-intellij-plugin#392]
**Describe the bug**

我在流程图中的节点设置了 Assignee 值，分别为${assignee0}、${assignee1}、${assignee2}、${assignee3}，并且流程成功部署；启动流程的时候我有通过Map对象上传assignee的值，为什么启动流程后 act_ru_task 表中 ASSIGNEE_ 字段为空，按理来说值应该为 “李四”。

**To Reproduce**

**BPMN definition**

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<diagram xmlns="http://www.omg.com/di/1.0.0">
<!-- BPMN to use to reproduce the issue -->
</diagram>
```

**Expected behavior**

启动流程后 act_ru_task 表中 ASSIGNEE_ 字段值应该为${assignee0}的值。

**Screenshots**

![image](https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/92110217/8faf3949-a455-4f9a-a4a1-70397f9846f6)

![image](https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/92110217/6c043100-29ce-445c-bf8b-ab452aaf83bc)

![image](https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/92110217/a161fd08-3bc3-497d-81a1-140f7dc3de21)

![image](https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/92110217/84dc128b-c213-4e97-b28d-e47a9feefc76)

**IntelliJ version (please complete the following information):**
 - Edition: [e.g. Ultimate]
 - Version [e.g. 2020.1]
 
Intellij idea 2021.3.1

**Additional context**

**Comment by valb3r** [comment]
@Yuqn 
Can't reproduce the issue, are you sure that you have correct test setup (I'm using pure Spring Boot integration test (with SpEL), but I don't see which Expression Language is used in your test case:

<img width="882" alt="Screenshot 2024-05-15 at 11 36 19" src="https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/18463491/f3e9a0e3-fe55-4936-8514-7ae7834db632">
<img width="837" alt="Screenshot 2024-05-15 at 11 36 32" src="https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/18463491/3a1f1393-a6eb-4567-b442-20688b6e4c4d">
<img width="1079" alt="Screenshot 2024-05-15 at 11 37 43" src="https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/18463491/8d907165-0985-4472-989a-498a8a334333">

**Comment by Yuqn** [comment]
我把任务删除，重新部署、启动就没有这种情况了
