### ISSUE TITLE
我想在连接线上通过流程变量实现流程分支，是否存在此功能

### ISSUE THREAD

**Issue by Yuqn** [valb3r/flowable-bpmn-intellij-plugin#393]
**Is your feature request related to a problem? Please describe.**

我创建了一个请假流程，内容为：创建出差申请 -> 部门经理审批 -> 总经理审批 -> 财务审批。当请假时间小于三天时，流程为 创建出差申请 -> 部门经理审批-> 财务审批；当请假时间大于等于三天时，流程为 创建出差 -> 部门经理审批 -> 总经理审批 -> 财务审批。

在 activiti 插件中，为两个审批模块之间的连线提供了 Condition 值，用于判断请假时间，从而达到不同效果，如下：
![image](https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/92110217/2e8d9845-26f0-433c-8683-97e47710fb1e)
![image](https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/92110217/ea0c38f0-5965-4bd0-9d62-b4b273ce350f)

该插件目前是否提供类似上面的 Condition 值用于设置流程变量呢？或者后续会提供该方法？

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by valb3r** [comment]
@Yuqn Thanks for feedback, I think this is already supported and is called "Condition expression":

感谢您的反馈，我认为这已经得到支持，称为“条件表达式”：

<img width="749" alt="Screenshot 2024-05-15 at 09 27 07" src="https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/18463491/cff5f95b-20b2-45a6-a2d0-a2a6bc111ff4">

**Comment by Yuqn** [comment]
嗯嗯，谢谢支持
