### ISSUE TITLE
IntelliJ community edition support

### ISSUE THREAD

**Issue by valb3r** [valb3r/flowable-bpmn-intellij-plugin#73]
**Is your feature request related to a problem? Please describe.**
Support for IntelliJ community edition.
Currently language injection feature and process debugging requires Ultimate edition of IntelliJ. Both features can have workarounds to support Community editions.

**Comment by coiouhkc** [comment]
Is there a feature branch or distribution without he above-mentioned features for community edition?

**Comment by valb3r** [comment]
@coiouhkc No there is no such branch as currently it looks like a lot of work for same features delivered. If there will be 10+ votes for the issue, priority can be reconsidered due to demand

**Comment by valb3r** [comment]
IJ Community and other IDEs are supported (in basic form) from v0.5.4
