### ISSUE TITLE
Wrong size of 'start' and 'finish' button 

### ISSUE THREAD

**Issue by elroman** [valb3r/flowable-bpmn-intellij-plugin#75]
**Describe the bug**
When open BPMN schema buttons start and finish have an incorrect color filling (color filling is much bigger than button icons). 

**To Reproduce**
1. open BPMN schema
2. look to start and stop button

**Expected behavior**
color doesn't cross the border of button icons

**Screenshots**
![image](https://user-images.githubusercontent.com/8805422/83498250-4f590200-a4c4-11ea-941b-e67f3881034d.png)

**IntelliJ version (please complete the following information):**
 - Edition: [e.g. Ultimate]
 - Version [e.g. 2020.1]

**Comment by valb3r** [comment]
Fixed with 
https://github.com/valb3r/flowable-bpmn-intellij-plugin/commit/70693d430cf0b09aadb1443f9e40db249e9ecac8
